open-eid/updater

- CMakeLists.txt
> Use Developer ID certificates

- CMakeLists.txt
> Use on signing sha256 timestamp

- ScheduledUpdateTask.cpp
> Fix day of month selection

- CMakeLists.txt
- idupdater.wxs
> Add custom WIX Welcome screen

- idupdater.wxs
> Use VS140 runtimes

- CMakeLists.txt
> Change version number

- Application.cpp
- CMakeLists.txt
- idupdater.wxs
- qt.conf
> Don't alter arguments, breaks file open with special characters

- prefPane/Base.lproj/ID_updater.xib
- prefPane/id-updater-helper.m
> Fix compiler warnings

- prefPane/id-updater.m
- prefPane/update.h
- prefPane/update.m
> Show OpenSC version

- .travis.yml
- CMakeLists.txt
- ScheduledUpdateTask.cpp
- idupdater.cpp
- prefPane/Base.lproj/ID_updater.xib
- prefPane/id-updater.m
- prefPane/update.h
- prefPane/update.m
> Update component lists and versions

- idupdater.wxs
- IB-5209
Signed-off-by: Toomas Uudisaru <toomas.uudisaru@aktors.ee>
> Add Qt SVG component to the installed libraries

- .travis.yml
- Application.cpp
- CMakeLists.txt
- RELEASE-NOTES.md
- idupdater.rc
- prefPane/update.m
> Update version number

- idupdater.wxs
IB-5275
Signed-off-by: Toomas Uudisaru <toomas.uudisaru@aktors.ee>
> Add missing qsvg.dll to win open-eid distribution

- CMakeLists.txt
> Increase version and enable compiler deprecated declarations

- prefPane/id-updater-helper.m
'dataFromPropertyList:format:errorDescription:' is deprecated
IB-5467
> Fix warning

- prefPane/update.m
'connectionWithRequest:delegate:'
IB-5467
> Fix warning and use NSURLSession instead

- prefPane/id-updater.m
- prefPane/update.h
- prefPane/update.m
> Fix memory leaks and reuse same code

- prefPane/Base.lproj/ID_updater.xib
- prefPane/en.lproj/Localizable.strings
- prefPane/et.lproj/Localizable.strings
- prefPane/id-updater.m
- prefPane/ru.lproj/Localizable.strings
- prefPane/update.h
- prefPane/update.m
> Add IDEMIA packages

- idupdater.wxs
> Include qgif.dll plugin

- CMakeLists.txt
- RELEASE-NOTES.md
> Update release notes and increase version number

- CMakeLists.txt
> Notarize application

- prefPane/id-updater.m
> Parse cert before xar_close

- prefPane/Base.lproj/ID_updater.xib
> Allow to select version info text

- prefPane/id-updater.m
> Show only installed components

- CMakeLists.txt
- idupdater.wxs
> OpenSSL 1.1.1c

- CMakeLists.txt
- RELEASE-NOTES.md
- idupdater.cpp
- idupdater.wxs
> Include Qt 5.12 qwindowsviasta style plugin

- prefPane/Base.lproj/ID_updater.xib
- prefPane/id-updater.m
> Show server message multiLine textfield

- CMakeLists.txt
- RELEASE-NOTES.md
- idupdater.rc
> Update copyright year and changelog

- prefPane/Info.plist.cmake
> Enable dark mode when building old sdk

- .travis.yml
- CMakeLists.txt
- RELEASE-NOTES.md
> Increase version number

- prefPane/Info.plist.cmake
> Fix autolayout issue macOS 10.15

- .travis.yml
- CMakeLists.txt
- RELEASE-NOTES.md
- prefPane/id-updater-helper.m
- prefPane/id-updater.m
- prefPane/update.h
- prefPane/update.m
> Verify CMS signatures

- CMakeLists.txt
> Enable Integrity check

- prefPane/id-updater.m
> Update UI in main thread

- idupdater.ui
- idupdater_et.ts
- idupdater_ru.ts
- prefPane/Base.lproj/ID_updater.xib
- prefPane/en.lproj/Localizable.strings
- prefPane/et.lproj/Localizable.strings
- prefPane/id-updater.m
- prefPane/ru.lproj/Localizable.strings
IB-6252
Signed-off-by: Kristel Merilain <kristel.merilain@ria.ee>
> Update id.ee urls

- .github/workflows/build.yml
- README.md
- idupdater.wxs
> Include MSVC runtimes

- CMakeLists.txt
> Fix Task scheduler

- CMakeLists.txt
> Fix code signing

- .github/workflows/build.yml
- Application.cpp
- Application.h
- CMakeLists.txt
- idupdater.rc
> Fix universal binary build

- idupdater.cpp
- idupdater.h
- idupdater.ui
- prefPane/Base.lproj/ID_updater.xib
- prefPane/update.m
> Show update when message is available

- .github/workflows/build.yml
- CMakeLists.txt
- idupdater.wxs
> Use OpenSSL from vcpkg

- prefPane/Base.lproj/ID_updater.xib
IB-6995
Signed-off-by: Jelena Sanko <jelena@raulwalter.com>
> Fix Scroll View (changelog url)

- prefPane/id-updater.m
IB-6996
Signed-off-by: Jelena Sanko <jelena@raulwalter.com>
> Fix the problem of displaying the user notification message

- .github/workflows/build.yml
- CMakeLists.txt
- prefPane/en.lproj/Localizable.strings
- prefPane/et.lproj/Localizable.strings
- prefPane/id-updater.m
- prefPane/ru.lproj/Localizable.strings
> Add web-eid to diagnostics

- idupdater.rc
> Update copyright year

- .github/workflows/build.yml
- Application.cpp
- CMakeLists.txt
- ScheduledUpdateTask.cpp
- idupdater.cpp
- idupdater.wxs
> Qt 6 support

- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- idupdater.cpp
- idupdater.h
- prefPane/id-updater.m
- prefPane/update.h
- prefPane/update.m
> Fetch update message from URL

- .github/workflows/build.yml
- Application.cpp
- idupdater.cpp
- idupdater.h
> Instance blocks application quit under windows

- prefPane/Base.lproj/ID_updater.xib
- prefPane/en.lproj/ID_updater.strings
- prefPane/en.lproj/Localizable.strings
- prefPane/et.lproj/ID_updater.strings
- prefPane/et.lproj/InfoPlist.strings
- prefPane/et.lproj/Localizable.strings
- prefPane/id-updater.m
- prefPane/ru.lproj/ID_updater.strings
- prefPane/ru.lproj/InfoPlist.strings
- prefPane/ru.lproj/Localizable.strings
- prefPane/update.m
> New updater style for macOS

- idupdater.cpp
> Do certificate pinning only updater message url

- .github/workflows/build.yml
- CMakeLists.txt
- RELEASE-NOTES.md
- idupdater.rc
> Fix Github actions and increase version number

- CMakeLists.txt
> Update Copyright year and cleanup scripts

- prefPane/id-updater.m
> Update LastCheck always

- CMakeLists.txt
- prefPane/Base.lproj/ID_updater.xib
- prefPane/en.lproj/ID_updater.strings
- prefPane/et.lproj/ID_updater.strings
- prefPane/id-updater.m
- prefPane/ru.lproj/ID_updater.strings
> Show version numbers

- .github/workflows/build.yml
- Application.cpp
- idupdater.cpp
> Remove unicode char from User-Agent to fix HTTP/2 connection

- idupdater.cpp
> Revert old behaviour

- .github/workflows/build.yml
- CMakeLists.txt
- idupdater.wxs
> Remove obsolete platforms from GitHub Actions

- .github/workflows/build.yml
- idupdater.wxs
> Make OpenSSL 3.0.8 as default

- .github/workflows/build.yml
- Application.cpp
- idupdater.cpp
> Use uiLanguages preferences

- .github/workflows/build.yml
- CMakeLists.txt
- idupdater.wxs
> Remove Gemalto card support and update Qt 6.6.1

- CMakeLists.txt
- idupdater.rc
> Update copyright year and version number

- .github/workflows/build.yml
- CMakeLists.txt
- idupdater.wxs
> Wix 4.0 support

- .github/workflows/build.yml
> Fix build using fixed WIX extension version

- .github/workflows/build.yml
- idupdater.wxs
> Update Qt 6.7.1

- idupdater.wxs
> Qt Depends msvcp140_1/2 dlls

- Application.cpp
> Windows 11 theme is broken under Windows 11
